### ISSUE TITLE
Licensing needs fixing

### ISSUE THREAD

**Issue by pemensik** [dmorawetz/cargo-rpmstatus#2]
License declared by cargo-debstatus is very likely incomplete, because it does not contain any license trace used in original source of that, https://github.com/sfackler/cargo-tree. That contains MIT AND Apache-2.0 licenses, but not GPL-3.0. I have filled https://github.com/kpcyrd/cargo-debstatus/issues/41 on that project, but I think this project should fix the license anyway here. It seems to me some code were reused and that is obvious. But licensing does not indicate possible relation or original license. Because license commits were done by different people, it does not seem likely the code were relicensed by original author.

**Comment by pemensik** [comment]
I would suggest using SPDX license tags in files, which contain also parts of original project. To make which can be only GPL-3.0 and which have multiple licenses in single file.

**Comment by dmorawetz** [comment]
Thank you for your comments and your PR. I saw them just now due to holidays. As I am no expert with the licensing I need to look at this more closely as soon as I have time.

**Comment by pemensik** [comment]
I am no expert either, but I think the basics are simple enough. You can change license of parts you have made, but cannot change license of work done by someone other. Because it would be difficult to track license of different parts, open source projects usually require contributions to be under same license as original derived work.

I seems GNU GPL were chosen somehow arbitrary by cargo-debstatus and therefore it became unclear which files and their parts are under which license.

But the minimum we can do is to mark *all* files to be licensed both under GPL and original MIT AND Apache-2.0. Ideally mark in each file which licenses apply, if it is different than others.

Ideally each file should be marked with correct ``// SPDX-License-Identifier: MIT AND Apache-2.0 AND GPL-3.0``, unless that file contains only original or only new content. More on https://spdx.dev/learn/handling-license-info/. Though it should be first made clear on cargo-debstatus, then this project should clarify license of local changes.

Also source code archive should contain text of license for all licenses used.

**Comment by dmorawetz** [comment]
@pemensik I finally got to it. I applied the same license clarifications as cargo-debstatus. Thanks for your help and clarifications.
